first_name = input("Enter your first name: ")
last_name = input("Enter you last name here: ")
print(f"Hello {first_name} {last_name}!")
first_number = float(input("Give me a number: "))
second_number = float(input("Give me another number: "))
print(f"The sum of these 2 numbers is {first_number+second_number}")
print(f"The difference of these 2 numbers is {first_number-second_number}")
print(f"The product of these 2 numbers is {first_number*second_number}")
print(f"The quotient of these 2 numbers is {first_number/second_number}")
print(f"Have a great day!")
